# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eaf49a7b9907a5098a599fc0bfa0fefd3e74397534c8e3e41a24e2e9c8c19c0fb57e756bd2738ce16393d5ae903b9d3e1517182a063562b2a57655051d288c5

test:
  secret_key_base: e7a47f18a598e9fcd2975af590271dd8302566a9f0ecd505f84590cab5ef5dce2f17653c78f0b75d94ca2e94945e6a05957a0a20c8f9f333e3af9bdd5ee80af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
